name: Rust checks

permissions: {}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings

# Ubuntu versions: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

jobs:
  ubuntu_18_rust_stable:
    runs-on: ubuntu-18.04
    env:
      LANDLOCK_CRATE_TEST_ABI: 0
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust stable
      run: |
        rm ~/.cargo/bin/{cargo-fmt,rustfmt} || :
        rustup default stable
        rustup update

    - name: Run tests
      run: rustup run stable cargo test --verbose

  ubuntu_18_rust_msrv:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Get MSRV
      run: sed -n 's/^rust-version = "\([0-9.]\+\)"$/RUST_TOOLCHAIN=\1/p' Cargo.toml >> $GITHUB_ENV

    - name: Install Rust MSRV
      run: |
        rm ~/.cargo/bin/{cargo-fmt,rustfmt} || :
        rustup default ${{ env.RUST_TOOLCHAIN }}
        rustup update ${{ env.RUST_TOOLCHAIN }}

    - name: Build
      run: rustup run ${{ env.RUST_TOOLCHAIN }} cargo build --verbose

    - name: Build tests
      run: rustup run ${{ env.RUST_TOOLCHAIN }} cargo build --tests --verbose

  ubuntu_20_rust_stable:
    runs-on: ubuntu-20.04
    env:
      LANDLOCK_CRATE_TEST_ABI: 1
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust stable
      run: |
        rm ~/.cargo/bin/{cargo-fmt,rustfmt} || :
        rustup default stable
        rustup component add rustfmt clippy
        rustup update

    - name: Build
      run: rustup run stable cargo build --verbose

    - name: Run tests
      run: rustup run stable cargo test --verbose

    - name: Check format
      run: rustup run stable cargo fmt --all -- --check

    - name: Check source with Clippy
      run: rustup run stable cargo clippy -- --deny warnings

    - name: Check tests with Clippy
      run: rustup run stable cargo clippy --tests -- --deny warnings

    - name: Check documentation
      run: rustup run stable cargo doc --no-deps

  ubuntu_22_rust_stable:
    runs-on: ubuntu-22.04
    env:
      LANDLOCK_CRATE_TEST_ABI: 1
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust stable
      run: |
        rm ~/.cargo/bin/{cargo-fmt,rustfmt} || :
        rustup default stable
        rustup update

    - name: Run tests
      run: rustup run stable cargo test --verbose
